# Generated by Django 4.2.1 on 2023-05-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('title_post', models.CharField(max_length=50)),
                ('text_post', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.category')),
                ('post_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category_com',
            field=models.ManyToManyField(related_name='news', through='Board.PostCategory', to='Board.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('post_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.post')),
                ('user_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to='Board.user'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_com',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Board.user'),
        ),
    ]
