# Generated by Django 4.2.1 on 2023-05-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
