# Generated by Django 4.2.1 on 2023-05-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_remove_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_com',
            field=models.ManyToManyField(through='Board.PostCategory', to='Board.category'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
